name: coverage

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pdm install

      - name: Test with pytest
        run: |
          pdm run pytest --cov ignoro --cov-report term-missing --cov-report xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
