name: test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pdm install

      - name: Test with pytest
        run: |
          pdm run pytest ./tests

